pub const WINDOW_WIDTH: u32 = 1920;
pub const WINDOW_HEIGHT: u32 = 1080;

pub const PIXEL_SCALE: u32 = 8;

pub const WORLD_WIDTH: u32 = WINDOW_WIDTH / PIXEL_SCALE;
pub const WORLD_HEIGHT: u32 = WINDOW_HEIGHT / PIXEL_SCALE;

pub const MAX_INDEX: u32 = WORLD_WIDTH * WORLD_HEIGHT;

pub const WORLD_X_UPPER_BOUND: u32 = WORLD_WIDTH - 1;
pub const WORLD_Y_UPPER_BOUND: u32 = WORLD_HEIGHT - 1;
